# Generated by Django 4.1.4 on 2022-12-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
